version: "3"

volumes:
  model_cache:

services:
  model_server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    ports:
      - 5000:5000
    volumes:
      - model_cache:/root/.cache/huggingface:delegated
